### ISSUE TITLE
[Non-SSR] Dispatching route changes programatically (i.e. outside of the Link component) doesn't change the URL

### ISSUE THREAD

**Issue by reaysawa** [respond-framework/rudy#31]
Following my thoughts at https://github.com/respond-framework/rudy/issues/22, which I got lost in not being certain of which direction to go.

What I want to achieve is being able to change routes outside of the Link component; for instance, when using state-machinery with XState, Redux-Saga, or any other middleware which could trigger a route change outside of a React component.

If I use

`dispatch({ type: 'ABOUT', location: { kind: 'push' } })`

The page changes, but not the browser's URL.

I've tried to use redux-first-router but I'm having the same problem.

**Comment by hedgepigdaniel** [comment]
Hmm, that's surprising.

There's a few examples of routing actions being dispatched in the boilerplate example - do they not work? https://github.com/respond-framework/rudy/blob/master/packages/boilerplate/src/routes.js Otherwise if you can share a minimal repro I'd be happy to investigate.

the `location.kind` is unnecessary btw - `push` is the default.

**Comment by reaysawa** [comment]
It seems like the examples are using 'react-redux' which isn't the same connector I'm using in my project.

You can reproduce it, like on my end, like this:

```
git clone https://github.com/reaysawa/starter-saga-scss
cd starter-saga-scss
git checkout with-respond-rudy
yarn && yarn dev
```

When the Home Page is fired up (it's mostly just a blank page), click on **LINK TO ABOUT**. It will match and load up the AboutPage component but the URL in the browser doesn't change.

**Comment by hedgepigdaniel** [comment]
I had a look, and it looks like the sagas middleware prevents the Rudy middleware from being used. It works fine if you comment out the sagas middleware, or if the rudy middleware is first in the chain. Are you sure the sagas redux middleware is passing through the entire unmodified action to the Rudy middleware?

Not sure specifically what the problem is here, but one of our TODOs is to make Rudy middleware (as opposed to redux middleware) that implements sagas. That way it will be possible to choose what order the sagas happen relative to URL changes and other Rudy middlewares.

See examples of Rudy middlewares:
- Setting the page title: https://github.com/respond-framework/rudy/blob/master/packages/middleware-change-page-title/src/index.js
- Calling `thunk`, `beforeChange`, and other route callbacks: https://github.com/respond-framework/rudy/blob/master/packages/rudy/src/middleware/call/index.js

**Comment by reaysawa** [comment]
Thanks for the investigation @hedgepigdaniel. It was foolish of me to not assume the middleware composition was affecting it; but that's mostly because the route dispatching was still working, despite the effects of it not being committed to the URL. To put it short, I wasn't expect it to "only half work" with this current setup, since no misbehavings were being shown in the console.

From your explanation, the Saga Middleware is intervening with the aftermath of the actions, and thus the effects to update the URL aren't being realized, is that correct? So does the URL change only occurs after some special trigger? If so, can you please link me to where in the code this is? I've tried to search for uses of the history API but couldn't land at a significant point.

Since updating the URL is a side-effect and all, I wonder if it could be decoupled as another component which doesn't rely on Redux's context. Maybe that would be better than coming up with a middleware for this use case.

**Comment by hedgepigdaniel** [comment]
I'm not sure, but my impression is that the Rudy reducer is working (so it responds to the routing action as it is dispatched in your app). That is probably enough for your apps UI to update. But assuming the middleware is not working at all, that explains why the action is not transformed (the routing action doesn't have all the added keys like `prev`, etc when it gets to the store), and why the URL isn't changing.

Perhaps you could try wrapping the Rudy middleware before applying it to your store and seeing if the actions are getting to it at all. Maybe redux-saga is not passing them on at all?

If they are but for some reason Rudy is ignoring them:
- Here is the first line of code in the middleware when an action is received: https://github.com/respond-framework/rudy/blob/32979d1bcef5f6847b628b7bf0954bb861e36f04/packages/rudy/src/core/createRouter.js#L105-L106
- Here are all the default Rudy middlewares (they all exist inside the Rudy Redux middleware): https://github.com/respond-framework/rudy/blob/32979d1bcef5f6847b628b7bf0954bb861e36f04/packages/rudy/src/core/createRouter.js#L39-L54
- The `enter` middleware is the one that is responsible for setting the URL: https://github.com/respond-framework/rudy/blob/32979d1bcef5f6847b628b7bf0954bb861e36f04/packages/rudy/src/middleware/enter.js

**Comment by reaysawa** [comment]
I'm tempted to think the Saga middleware is halting Redux's resolvers. I'll try adding yet another side-effectful middleware from other packages and seeing if the pattern follows there - that being the case, rudy wouldn't be at fault. Also considering you provided a solution that's good enough for me, I'll close the issue. Feel free to re-open it under a different name (although I think the interaction layer with Saga et. al deserves it's own). Thanks for the help!
