### ISSUE TITLE
Set an action to be used a `replace` instead of `push`

### ISSUE THREAD

**Issue by JalilArfaoui** [respond-framework/rudy#35]
I don't use Rudy yet, but since I'm a user of RFR and this is the next gen ... I'm posting here. 

I really like navigating by only dispatch actions around (maybe I shouldn't ?). I allows me to use `onClick` a lot instead of `Link`s ...

One thing bothers me is that I can't `replace` my location this way. 

I would be helpful to be able to dispatch an action while indicating that we want `history` to `replace` location ... 

Example : 

```js
{
  type: 'SOME_PAGE',
  payload: {
    someParam: 'someValue'
  },
  meta: {
    replace: true
  }
}
```

What do you think ? Am I missing an simpler way ? 

The only thing I found right now is manually using `replace` but I need the to put the `path`, which I like to only let in one place (route config). 

Another solution would be able to feed `replace` with an action, like so : 

```js
replace({
  type: 'SOME_PAGE',
  payload: {
    someParam: 'someValue'
  }
}
```

What do you think @faceyspacey  ?

**Comment by hedgepigdaniel** [comment]
Going with your example, try this:

```javascript
import { redirect } from '@respond-framework/rudy';

dispatch(redirect({
  type: 'SOME_PAGE',
  payload: {
    someParam: 'someValue'
  },
});
```

> I really like navigating by only dispatch actions around (maybe I shouldn't ?). I allows me to use `onClick` a lot instead of `Link`s ...

Sure - but just a note: its good for SEO, (and some less common use cases like right clicking to open in a new tab) to have an `href` attribute on the link even if in most cases the JS handles it. The included `<Link />` component handles this for you.

I still like the style of only passing redux actions to the link component (never paths/URLs) since then you never need to hard code the URLs outside of routesMap.

**Comment by JalilArfaoui** [comment]
Hi @hedgepigdaniel 

Sorry, I completely forgot to answer you. 

I did find out about the `redirect` right after writing my message, and it is exactly what I was looking for. Thank you pointing it at me anyway. 

And thank you for the SEO advice, but not all applications are SEO concerned, fortunately :-) But thanks again.
